# Generated by Django 5.2.5 on 2025-08-28 11:28

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('asset_id', models.CharField(max_length=255, unique=True)),
                ('asset_type', models.CharField(choices=[('door', 'Door'), ('cnc', 'CNC Machine'), ('robot', 'Industrial Robot'), ('pump', 'Pump'), ('motor', 'Motor'), ('conveyor', 'Conveyor'), ('other', 'Other')], max_length=50)),
                ('make', models.CharField(max_length=255)),
                ('model', models.CharField(max_length=255)),
                ('serial_number', models.CharField(blank=True, max_length=255)),
                ('installation_date', models.DateField(blank=True, null=True)),
                ('location', models.CharField(blank=True, help_text='Physical location within site', max_length=255)),
                ('specifications', models.JSONField(blank=True, default=dict, help_text='Technical specifications')),
                ('tags', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='devices.site')),
            ],
            options={
                'unique_together': {('asset_id', 'site')},
            },
        ),
        migrations.CreateModel(
            name='AssetCycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cycle_type', models.CharField(help_text='Type of cycle (open/close, start/stop, etc.)', max_length=100)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('duration', models.DurationField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cycles', to='assets.asset')),
            ],
            options={
                'indexes': [models.Index(fields=['asset', 'start_time'], name='assets_asse_asset_i_3951bd_idx'), models.Index(fields=['asset', 'cycle_type', 'start_time'], name='assets_asse_asset_i_ceedaf_idx')],
            },
        ),
    ]
