# Generated by Django 5.2.5 on 2025-08-28 11:28

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelemetryPacket',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('upload_id', models.UUIDField(help_text='Client-generated upload identifier')),
                ('checksum', models.CharField(max_length=128)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('processed', 'Processed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('record_count', models.PositiveIntegerField(default=0)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telemetry_packets', to='devices.device')),
            ],
            options={
                'indexes': [models.Index(fields=['device', 'created_at'], name='telemetry_t_device__0bec4d_idx'), models.Index(fields=['status', 'created_at'], name='telemetry_t_status_fd3082_idx')],
                'unique_together': {('device', 'upload_id')},
            },
        ),
        migrations.CreateModel(
            name='TelemetryPoint',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField()),
                ('metric', models.CharField(max_length=255)),
                ('value', models.FloatField()),
                ('unit', models.CharField(blank=True, max_length=50)),
                ('meta', models.JSONField(blank=True, default=dict, help_text='Additional metadata')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telemetry_points', to='devices.device')),
            ],
            options={
                'indexes': [models.Index(fields=['device', 'timestamp'], name='telemetry_t_device__d8c000_idx'), models.Index(fields=['device', 'metric', 'timestamp'], name='telemetry_t_device__26fcdd_idx'), models.Index(fields=['metric', 'timestamp'], name='telemetry_t_metric_d62265_idx')],
            },
        ),
        migrations.CreateModel(
            name='TelemetryWindow',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField()),
                ('metric', models.CharField(max_length=255)),
                ('window_size_seconds', models.PositiveIntegerField(help_text='Size of the aggregation window')),
                ('statistics', models.JSONField(help_text='Aggregated statistics (rms, max, std, bandpower, etc.)')),
                ('sample_count', models.PositiveIntegerField(default=0)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telemetry_windows', to='devices.device')),
            ],
            options={
                'indexes': [models.Index(fields=['device', 'timestamp'], name='telemetry_t_device__3c37d5_idx'), models.Index(fields=['device', 'metric', 'timestamp'], name='telemetry_t_device__91749f_idx'), models.Index(fields=['metric', 'timestamp'], name='telemetry_t_metric_692f69_idx')],
            },
        ),
    ]
